### ISSUE TITLE
Ce même projet en JS

### ISSUE THREAD

**Issue by AlexisTM** [GauthLin/MaMaisonnette#1]
http://git.ecam.be/11128/dodo

**Comment by GauthLin** [comment]
Pourquoi avoir faire cela en JS et pas en python (ou autre langage) ?

**Comment by AlexisTM** [comment]
C'est simple !

Unicité du langage
Unicité de des implémentation des objets
Facilité de communications

=> serveur en Node.JS qui fait l'acquisition des données
=> serveur web en Node.JS 
=> application web en JS, HTM5, CSS3
=> base de donnée MongoDB JavaScript

Communications via Socket.IO, connection continue, nous ne devons pas faire de poll (poll = "Donne moi les valeurs ?" "voici les valeurs"), les valeurs sont envoyées dès que l'on en a.

De plus, on peut apprendre du Node.JS :3

**Comment by GauthLin** [comment]
J'ai regardé les codes et ne connaissant pas beaucoup le JS, c'est assez chaud patate. Je me dis qu'on va perdre beaucoup de temps rien que pour apprendre le langage alors qu'on a que 8 séances (déjà plus que 7)...

Tu nous conseilles vraiment d'utiliser Node.js ?

**Comment by AlexisTM** [comment]
Pas forcément en javascript... sauf que pour le serveur WEB, si vous voulez du real time, mieux vaut autre chose que du PHP (Utilisation de sockets/HTTP2)
